name: Redo dist

on:
  push:

  pull_request:


jobs:
  npm-run-dist:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - run: git status

      - run: npm install -dd

      - run: npm run dist

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: redo dist
